INIC PROGRAMMING LIBRARY: C:/Roland/AppsTeam/Misc/InicProgLib/trunk/ipl/inc/ipf.h File Reference
ipf.h File Reference
Internal header for functions to parse IPF data for INIC Programming Library.
#include <stdint.h>
#include "ipl.h"
Data Structures
struct Ipl_MetaData_
struct Ipl_IpfData_
Macros
#define STRINGTYPE_FW 0x01U
#define STRINGTYPE_CONFIG 0x02U /* CS + IS */
#define STRINGTYPE_CS 0x03U
#define STRINGTYPE_IS 0x04U
#define STRINGTYPE_PS 0x05U
#define STRINGTYPE_META 0x07U
#define STRING_MIN_LEN 32U
#define METAID_CHIPID 0x00000100U
#define METAID_CHIPPRGMEMSIZE 0x00000101U
#define METAID_CHIPPRGMEMPAGESIZE 0x00000102U
#define METAID_CHIPPRGMEMSECTIONSIZE 0x00000103U
#define METAID_CHIPNUMOFINFOMEMSECTIONS 0x00000104U
#define METAID_CHIPINFOMEMSECTIONSIZE 0x00000105U
#define METAID_CHIPTESTMEMSIZE 0x00000106U
#define METAID_CHIPCOMBINEDCFGSTARTADDR 0x00000107U
#define METAID_CHIPCOMBINEDCFGSIZE 0x00000108U
#define METAID_FWMAJORVERSION 0x00000200U
#define METAID_FWMINORVERSION 0x00000201U
#define METAID_FWRELEASEVERSION 0x00000202U
#define METAID_FWBUILDVERSION 0x00000203U
#define METAID_FWSIZE 0x00000204U
#define METAID_FWSTARTADDR 0x00000205U
#define METAID_BMSIZE 0x00000400U
#define METAID_BMMAXDATALENGTH 0x00000401U
#define METAID_CFGSFORMATVERSION 0x00000600U
#define METAID_CFGSCUSTMAJORVERSION 0x00000601U
#define METAID_CFGSCUSTMINORVERSION 0x00000602U
#define METAID_CFGSCUSTRELEASEVERSION 0x00000603U
#define METAID_CFGSSIZE 0x00000604U
#define METAID_CFGSDEFSTARTADDR 0x00000605U
#define METAID_CFGSSTDSTARTADDR 0x00000606U
#define METAID_CFGSOVRLSTARTADDR 0x00000607U
#define METAID_CFGSTESTSTARTADDR 0x00000608U
#define METAID_IDENTSFORMATVERSION 0x00000700U
#define METAID_IDENTSSIZE 0x00000701U
#define METAID_IDENTSSTDSTARTADDR 0x00000702U
#define METAID_IDENTSOVRLSTARTADDR 0x00000703U
#define METAID_IDENTSTESTSTARTADDR 0x00000704U
#define METAID_PATCHSSIZE 0x00000800U
#define METAID_PATCHSSTDSTARTADDR 0x00000801U
#define METAID_PATCHSTESTSTARTADDR 0x00000802U
#define METAID_TOOLTYPE 0x00000900U
#define METAID_TOOLMAJORVERSION 0x00000901U
#define METAID_TOOLMINORVERSION 0x00000902U
#define METAID_TOOLRELEASEVERSION 0x00000903U
#define METAID_TOOLBUILDVERSION 0x00000904U
#define METATYPE_UINT8 0x01U
#define METATYPE_UINT16 0x02U
#define METATYPE_UINT32 0x04U
#define METATYPE_INT8 0x09U
#define METATYPE_INT16 0x0AU
#define METATYPE_INT32 0x0CU
#define METATYPE_STRING 0x40U
#define METATYPE_ARRAY 0x80U
#define DEFAULTVAL_UINT8 0xFFU
#define DEFAULTVAL_UINT16 0xFFFFU
#define DEFAULTVAL_UINT32 0xFFFFFFFFU
#define DEFAULTVAL_STRING "\0"
#define VERSION_VALID 0x00U
#define VERSION_INVALID 0xFFU
Typedefs
typedef struct Ipl_MetaData_ Ipl_MetaData_t
typedef struct Ipl_IpfData_ Ipl_IpfData_t
Functions
uint8_t Ipl_ParseIpf (Ipl_IpfData_t *ipf, uint32_t lData, uint8_t pData[], uint8_t stringType)
void Ipl_ClrIpfData (Ipl_IpfData_t *ipf)
void Ipl_ClrMetaData (Ipl_IpfData_t *ipf)
Variables
Ipl_IpfData_t Ipl_IpfData
Detailed Description
Internal header for functions to parse IPF data for INIC Programming Library.
Author
Roland Trissl (RTR)
Note
For support related to this code contact http://www.microchip.com/support.
Definition in file ipf.h.
Macro Definition Documentation
DEFAULTVAL_STRING
#define DEFAULTVAL_STRING "\0"
Definition at line 98 of file ipf.h.
DEFAULTVAL_UINT16
#define DEFAULTVAL_UINT16 0xFFFFU
Definition at line 96 of file ipf.h.
DEFAULTVAL_UINT32
#define DEFAULTVAL_UINT32 0xFFFFFFFFU
Definition at line 97 of file ipf.h.
DEFAULTVAL_UINT8
#define DEFAULTVAL_UINT8 0xFFU
Definition at line 95 of file ipf.h.
METAID_BMMAXDATALENGTH
#define METAID_BMMAXDATALENGTH 0x00000401U
Definition at line 62 of file ipf.h.
METAID_BMSIZE
#define METAID_BMSIZE 0x00000400U
Definition at line 61 of file ipf.h.
METAID_CFGSCUSTMAJORVERSION
#define METAID_CFGSCUSTMAJORVERSION 0x00000601U
Definition at line 64 of file ipf.h.
METAID_CFGSCUSTMINORVERSION
#define METAID_CFGSCUSTMINORVERSION 0x00000602U
Definition at line 65 of file ipf.h.
METAID_CFGSCUSTRELEASEVERSION
#define METAID_CFGSCUSTRELEASEVERSION 0x00000603U
Definition at line 66 of file ipf.h.
METAID_CFGSDEFSTARTADDR
#define METAID_CFGSDEFSTARTADDR 0x00000605U
Definition at line 68 of file ipf.h.
METAID_CFGSFORMATVERSION
#define METAID_CFGSFORMATVERSION 0x00000600U
Definition at line 63 of file ipf.h.
METAID_CFGSOVRLSTARTADDR
#define METAID_CFGSOVRLSTARTADDR 0x00000607U
Definition at line 70 of file ipf.h.
METAID_CFGSSIZE
#define METAID_CFGSSIZE 0x00000604U
Definition at line 67 of file ipf.h.
METAID_CFGSSTDSTARTADDR
#define METAID_CFGSSTDSTARTADDR 0x00000606U
Definition at line 69 of file ipf.h.
METAID_CFGSTESTSTARTADDR
#define METAID_CFGSTESTSTARTADDR 0x00000608U
Definition at line 71 of file ipf.h.
METAID_CHIPCOMBINEDCFGSIZE
#define METAID_CHIPCOMBINEDCFGSIZE 0x00000108U
Definition at line 54 of file ipf.h.
METAID_CHIPCOMBINEDCFGSTARTADDR
#define METAID_CHIPCOMBINEDCFGSTARTADDR 0x00000107U
Definition at line 53 of file ipf.h.
METAID_CHIPID
#define METAID_CHIPID 0x00000100U
Definition at line 46 of file ipf.h.
METAID_CHIPINFOMEMSECTIONSIZE
#define METAID_CHIPINFOMEMSECTIONSIZE 0x00000105U
Definition at line 51 of file ipf.h.
METAID_CHIPNUMOFINFOMEMSECTIONS
#define METAID_CHIPNUMOFINFOMEMSECTIONS 0x00000104U
Definition at line 50 of file ipf.h.
METAID_CHIPPRGMEMPAGESIZE
#define METAID_CHIPPRGMEMPAGESIZE 0x00000102U
Definition at line 48 of file ipf.h.
METAID_CHIPPRGMEMSECTIONSIZE
#define METAID_CHIPPRGMEMSECTIONSIZE 0x00000103U
Definition at line 49 of file ipf.h.
METAID_CHIPPRGMEMSIZE
#define METAID_CHIPPRGMEMSIZE 0x00000101U
Definition at line 47 of file ipf.h.
METAID_CHIPTESTMEMSIZE
#define METAID_CHIPTESTMEMSIZE 0x00000106U
Definition at line 52 of file ipf.h.
METAID_FWBUILDVERSION
#define METAID_FWBUILDVERSION 0x00000203U
Definition at line 58 of file ipf.h.
METAID_FWMAJORVERSION
#define METAID_FWMAJORVERSION 0x00000200U
Definition at line 55 of file ipf.h.
METAID_FWMINORVERSION
#define METAID_FWMINORVERSION 0x00000201U
Definition at line 56 of file ipf.h.
METAID_FWRELEASEVERSION
#define METAID_FWRELEASEVERSION 0x00000202U
Definition at line 57 of file ipf.h.
METAID_FWSIZE
#define METAID_FWSIZE 0x00000204U
Definition at line 59 of file ipf.h.
METAID_FWSTARTADDR
#define METAID_FWSTARTADDR 0x00000205U
Definition at line 60 of file ipf.h.
METAID_IDENTSFORMATVERSION
#define METAID_IDENTSFORMATVERSION 0x00000700U
Definition at line 72 of file ipf.h.
METAID_IDENTSOVRLSTARTADDR
#define METAID_IDENTSOVRLSTARTADDR 0x00000703U
Definition at line 75 of file ipf.h.
METAID_IDENTSSIZE
#define METAID_IDENTSSIZE 0x00000701U
Definition at line 73 of file ipf.h.
METAID_IDENTSSTDSTARTADDR
#define METAID_IDENTSSTDSTARTADDR 0x00000702U
Definition at line 74 of file ipf.h.
METAID_IDENTSTESTSTARTADDR
#define METAID_IDENTSTESTSTARTADDR 0x00000704U
Definition at line 76 of file ipf.h.
METAID_PATCHSSIZE
#define METAID_PATCHSSIZE 0x00000800U
Definition at line 77 of file ipf.h.
METAID_PATCHSSTDSTARTADDR
#define METAID_PATCHSSTDSTARTADDR 0x00000801U
Definition at line 78 of file ipf.h.
METAID_PATCHSTESTSTARTADDR
#define METAID_PATCHSTESTSTARTADDR 0x00000802U
Definition at line 79 of file ipf.h.
METAID_TOOLBUILDVERSION
#define METAID_TOOLBUILDVERSION 0x00000904U
Definition at line 84 of file ipf.h.
METAID_TOOLMAJORVERSION
#define METAID_TOOLMAJORVERSION 0x00000901U
Definition at line 81 of file ipf.h.
METAID_TOOLMINORVERSION
#define METAID_TOOLMINORVERSION 0x00000902U
Definition at line 82 of file ipf.h.
METAID_TOOLRELEASEVERSION
#define METAID_TOOLRELEASEVERSION 0x00000903U
Definition at line 83 of file ipf.h.
METAID_TOOLTYPE
#define METAID_TOOLTYPE 0x00000900U
Definition at line 80 of file ipf.h.
METATYPE_ARRAY
#define METATYPE_ARRAY 0x80U
Definition at line 93 of file ipf.h.
METATYPE_INT16
#define METATYPE_INT16 0x0AU
Definition at line 90 of file ipf.h.
METATYPE_INT32
#define METATYPE_INT32 0x0CU
Definition at line 91 of file ipf.h.
METATYPE_INT8
#define METATYPE_INT8 0x09U
Definition at line 89 of file ipf.h.
METATYPE_STRING
#define METATYPE_STRING 0x40U
Definition at line 92 of file ipf.h.
METATYPE_UINT16
#define METATYPE_UINT16 0x02U
Definition at line 87 of file ipf.h.
METATYPE_UINT32
#define METATYPE_UINT32 0x04U
Definition at line 88 of file ipf.h.
METATYPE_UINT8
#define METATYPE_UINT8 0x01U
Definition at line 86 of file ipf.h.
STRING_MIN_LEN
#define STRING_MIN_LEN 32U
Definition at line 44 of file ipf.h.
STRINGTYPE_CONFIG
#define STRINGTYPE_CONFIG 0x02U /* CS + IS */
Definition at line 39 of file ipf.h.
STRINGTYPE_CS
#define STRINGTYPE_CS 0x03U
Definition at line 40 of file ipf.h.
STRINGTYPE_FW
#define STRINGTYPE_FW 0x01U
Definition at line 38 of file ipf.h.
STRINGTYPE_IS
#define STRINGTYPE_IS 0x04U
Definition at line 41 of file ipf.h.
STRINGTYPE_META
#define STRINGTYPE_META 0x07U
Definition at line 43 of file ipf.h.
STRINGTYPE_PS
#define STRINGTYPE_PS 0x05U
Definition at line 42 of file ipf.h.
VERSION_INVALID
#define VERSION_INVALID 0xFFU
Definition at line 101 of file ipf.h.
VERSION_VALID
#define VERSION_VALID 0x00U
Definition at line 100 of file ipf.h.
Typedef Documentation
Ipl_IpfData_t
typedef struct Ipl_IpfData_ Ipl_IpfData_t
Ipl_MetaData_t
typedef struct Ipl_MetaData_ Ipl_MetaData_t
Function Documentation
Ipl_ClrIpfData()
void Ipl_ClrIpfData (Ipl_IpfData_t * ipf)
Ipl_ClrMetaData()
void Ipl_ClrMetaData (Ipl_IpfData_t * ipf)
Ipl_ParseIpf()
uint8_t Ipl_ParseIpf (Ipl_IpfData_t * ipf, uint32_t lData, uint8_t pData[], uint8_t stringType)
Referenced by OS81050_ProgConfigString(), OS81050_ProgFirmware(), OS81060_ProgConfigString(), OS81110_ProgConfigString(), and OS81110_ProgFirmware().
Variable Documentation
Ipl_IpfData
Ipl_IpfData_t Ipl_IpfData
Referenced by OS81050_ProgConfigString(), OS81050_ProgFirmware(), OS81060_ProgConfigString(), OS81110_ProgConfigString(), and OS81110_ProgFirmware().