INIC PROGRAMMING LIBRARY: C:/Roland/AppsTeam/Misc/InicProgLib/trunk/ipl/opt/src/ipl_81082.c File Reference
ipl_81082.c File Reference
Internal OS81082 specific functions for INIC Programming Library.
#include <stdint.h>
#include "ipl_cfg.h"
#include "ipl.h"
#include "ipf.h"
#include "ipl_81082.h"
#include "ipl_81050.h"
Functions
uint8_t OS81082_ProgFirmware (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ProgConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ProgConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ProgIdentString (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ProgPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ProgTestPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ProgTestConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81082_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Detailed Description
Internal OS81082 specific functions for INIC Programming Library.
Author
Roland Trissl (RTR)
Note
For support related to this code contact http://www.microchip.com/support.
Definition in file ipl_81082.c.
Function Documentation
OS81082_ProgConfigString()
uint8_t OS81082_ProgConfigString (uint32_t lData, uint8_t pData[])
Definition at line 49 of file ipl_81082.c.
 {
     return OS81050_ProgConfigString(lData, pData);
 }
References OS81050_ProgConfigString().
OS81082_ProgConfiguration()
uint8_t OS81082_ProgConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 66 of file ipl_81082.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81082_ProgConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81082_ProgFirmware()
uint8_t OS81082_ProgFirmware (uint32_t lData, uint8_t pData[])
Definition at line 42 of file ipl_81082.c.
 {
     return OS81050_ProgFirmware(lData, pData);
 }
References OS81050_ProgFirmware().
OS81082_ProgIdentString()
uint8_t OS81082_ProgIdentString (uint32_t lData, uint8_t pData[])
Definition at line 73 of file ipl_81082.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81082_ProgIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81082_ProgPatchString()
uint8_t OS81082_ProgPatchString (uint32_t lData, uint8_t pData[])
Definition at line 80 of file ipl_81082.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81082_ProgPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81082_ProgTestConfigString()
uint8_t OS81082_ProgTestConfigString (uint32_t lData, uint8_t pData[])
Definition at line 101 of file ipl_81082.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81082_ProgTestConfigString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81082_ProgTestConfiguration()
uint8_t OS81082_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 87 of file ipl_81082.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81082_ProgTestConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81082_ProgTestIdentString()
uint8_t OS81082_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Definition at line 108 of file ipl_81082.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81082_ProgTestIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81082_ProgTestPatchString()
uint8_t OS81082_ProgTestPatchString (uint32_t lData, uint8_t pData[])
Definition at line 94 of file ipl_81082.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81082_ProgTestPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81082_ReadConfigStringVersion()
uint8_t OS81082_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
Definition at line 59 of file ipl_81082.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81082_ReadConfigStringVersion returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.