INIC PROGRAMMING LIBRARY: C:/Roland/AppsTeam/Misc/InicProgLib/trunk/ipl/opt/src/ipl_81050.c File Reference
ipl_81050.c File Reference
Internal OS81050 specific functions for INIC Programming Library.
#include <stdint.h>
#include "ipl_cfg.h"
#include "ipl.h"
#include "ipf.h"
#include "ipl_81050.h"
Functions
uint8_t OS81050_ProgFirmware (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ProgConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ProgConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ProgIdentString (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ProgPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ProgTestPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ProgTestConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81050_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Detailed Description
Internal OS81050 specific functions for INIC Programming Library.
Author
Roland Trissl (RTR)
Note
For support related to this code contact http://www.microchip.com/support.
Definition in file ipl_81050.c.
Function Documentation
OS81050_ProgConfigString()
uint8_t OS81050_ProgConfigString (uint32_t lData, uint8_t pData[])
Definition at line 162 of file ipl_81050.c.
 {
     uint8_t  res;
     uint32_t loop, page;
     Ipl_Trace(IPL_TRACETAG_INFO, "OS81050_ProgConfigString called");
     /* Get addresses and sizes from metadata */
     res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_META);
     if (IPL_RES_OK == res)
     {
         /* Check if IPF contains proper ConfigString */
         res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_CONFIG);
         if (IPL_RES_OK == res)
         {
             /* Check if IPF fits to INIC */
             res = Ipl_CheckChipId();
             if (IPL_RES_OK == res)
             {
                 /* Erase INIC CS */
                 Ipl_ClrTel();
                 Ipl_IplData.Tel[0] = CMD_LEG_ERASECS;
                 Ipl_IplData.Tel[1] = 0x67U;
                 Ipl_IplData.TelLen = CMD_LEG_ERASECS_TXLEN;
                 res = Ipl_ExecInicCmd();
                 if (IPL_RES_OK == res)
                 {
                     /* Clear CRC */
                     Ipl_ClrTel();
                     Ipl_IplData.Tel[0] = CMD_CLEARCRC;
                     Ipl_IplData.TelLen = CMD_CLEARCRC_TXLEN;
                     res = Ipl_ExecInicCmd();
                     if (IPL_RES_OK == res)
                     {
                         /* Write CS */
                         for(page=0U; page<=3U; page++)
{
                             Ipl_IplData.Tel[0] = CMD_LEG_WRITECS;
                             Ipl_IplData.Tel[1] = 0x00U;
                             Ipl_IplData.Tel[2] = (uint8_t) page*32U;
                             Ipl_IplData.Tel[3] = 0x20U;
                             for(loop=0U; loop<32U; loop++)
{
                                 Ipl_IplData.Tel[4U+loop] = Ipl_PData(loop+Ipl_IpfData.StringOffset+(uint32_t) (page*32U), lData, pData);
                             }
                             Ipl_IplData.TelLen = 36U;
                             res = Ipl_ExecInicCmd();
                             Ipl_ProgressIndicator((page*32U), Ipl_IpfData.StringSize);
                         }
                         if (IPL_RES_OK == res)
{
                             /* Get CRC */
                             Ipl_ClrTel();
                             Ipl_IplData.Tel[0] = CMD_GETCRC;
                             Ipl_IplData.Tel[3] = 0x2U;
                             Ipl_IplData.TelLen = CMD_GETCRC_TXLEN;
                             res = Ipl_ExecInicCmd();
                             if(IPL_RES_OK == res)
{
                                 if ( (Ipl_IplData.Tel[4] != 0x00U) || (Ipl_IplData.Tel[5] != 0x00U) )
{
                                     res = IPL_RES_ERR_WRONG_CRC;
                                 }
                             }
                         }
                     }
                 }
             }
         }
     }
     Ipl_ProgressIndicator(1U, 1U); /* Set Progress Indicator to 100 */
     Ipl_Trace(Ipl_TraceTag(res), "OS81050_ProgConfigString returned 0x%02X", res);
     return res;
 }
References CMD_CLEARCRC, CMD_CLEARCRC_TXLEN, CMD_GETCRC, CMD_GETCRC_TXLEN, CMD_LEG_ERASECS, CMD_LEG_ERASECS_TXLEN, CMD_LEG_WRITECS, Ipl_CheckChipId(), Ipl_ClrTel(), Ipl_ExecInicCmd(), Ipl_IpfData, Ipl_IplData, Ipl_ParseIpf(), Ipl_PData(), Ipl_ProgressIndicator(), IPL_RES_ERR_WRONG_CRC, IPL_RES_OK, Ipl_Trace(), Ipl_TraceTag(), IPL_TRACETAG_INFO, Ipl_IpfData_::StringOffset, Ipl_IpfData_::StringSize, STRINGTYPE_CONFIG, STRINGTYPE_META, Ipl_IplData_::Tel, and Ipl_IplData_::TelLen.
Referenced by OS81082_ProgConfigString().
OS81050_ProgConfiguration()
uint8_t OS81050_ProgConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 247 of file ipl_81050.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81050_ProgConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81050_ProgFirmware()
uint8_t OS81050_ProgFirmware (uint32_t lData, uint8_t pData[])
Definition at line 41 of file ipl_81050.c.
 {
     uint8_t  res;
     uint32_t loop, adr, startadr, stopadr;
     Ipl_Trace(IPL_TRACETAG_INFO, "OS81050_ProgFirmware called");
     /* Get addresses and sizes from metadata */
     res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_META);
     if (IPL_RES_OK == res)
     {
         /* Check if IPF contains proper Firmware */
         res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_FW);
         if (IPL_RES_OK == res)
         {
             /* Check if IPF fits to INIC */
             res = Ipl_CheckChipId();
             if (IPL_RES_OK == res)
             {
                 /* Erase INIC FW */
                 Ipl_ClrTel();
                 Ipl_IplData.Tel[0] = CMD_ERASEPROGMEM;
                 Ipl_IplData.Tel[1] = 0x08U;
                 Ipl_IplData.Tel[2] = 0x77U;
                 Ipl_IplData.TelLen = CMD_ERASEPROGMEM_TXLEN;
                 res = Ipl_ExecInicCmd();
                 if (IPL_RES_OK == res)
                 {
                     /* Select Flash Page 0 */
                     Ipl_ClrTel();
                     Ipl_IplData.Tel[0] = CMD_SETPROGMEMPAGE;
                     Ipl_IplData.Tel[1] = 0x0U;
                     Ipl_IplData.TelLen = CMD_SETPROGMEMPAGE_TXLEN;
                     res = Ipl_ExecInicCmd();
                     if (IPL_RES_OK == res)
                     {
                         /* Clear CRC */
                         Ipl_ClrTel();
                         Ipl_IplData.Tel[0] = CMD_CLEARCRC;
                         Ipl_IplData.TelLen = CMD_CLEARCRC_TXLEN;
                         res = Ipl_ExecInicCmd();
                         if (IPL_RES_OK == res)
{
                             /* Write FW Page 0 */
                             startadr = 0x2000U;
                             adr      = startadr;
                             stopadr = 0x10000U;
                             while ( (adr < stopadr) && (IPL_RES_OK == res) )
{
                                 Ipl_IplData.Tel[0] = CMD_WRITEPROGMEM;
                                 Ipl_IplData.Tel[1] = (adr >> 8U) & 0xFFU;
                                 Ipl_IplData.Tel[2] = adr & 0xFFU;
                                 Ipl_IplData.Tel[3] = 0x20U;
                                 for(loop=0U; loop<32U; loop++)
{
                                     Ipl_IplData.Tel[4U+loop] = Ipl_PData((loop+Ipl_IpfData.StringOffset+adr)-startadr, lData, pData);
                                 }
                                 Ipl_IplData.TelLen = 36U;
                                 res = Ipl_ExecInicCmd();
                                 adr += 0x20U;
                                 Ipl_ProgressIndicator(adr-startadr, Ipl_IpfData.StringSize);
                             }
                             if (IPL_RES_OK == res)
{
                                 /* Select Flash Page 1 */
                                 Ipl_ClrTel();
                                 Ipl_IplData.Tel[0] = CMD_SETPROGMEMPAGE;
                                 Ipl_IplData.Tel[1] = 0x1U;
                                 Ipl_IplData.TelLen = CMD_SETPROGMEMPAGE_TXLEN;
                                 res = Ipl_ExecInicCmd();
                                 if (IPL_RES_OK == res)
{
                                     /* Write FW Page 1 */
                                     adr     = 0x10000U;
                                     stopadr = 0x1FBFFU;
                                     while ( (adr < stopadr) && (IPL_RES_OK == res) )
{
                                         Ipl_IplData.Tel[0] = CMD_WRITEPROGMEM;
                                         Ipl_IplData.Tel[1] = (adr >> 8U) & 0xFFU;
                                         Ipl_IplData.Tel[2] = adr & 0xFFU;
                                         Ipl_IplData.Tel[3] = 0x20U;
                                         for(loop=0U; loop<32U; loop++)
{
                                             Ipl_IplData.Tel[4U+loop] = Ipl_PData((loop+Ipl_IpfData.StringOffset+adr)-startadr, lData, pData);
                                         }
                                         Ipl_IplData.TelLen = 36U;
                                         res = Ipl_ExecInicCmd();
                                         adr += 0x20U;
                                         Ipl_ProgressIndicator(adr-startadr, Ipl_IpfData.StringSize);
                                     }
                                     if (IPL_RES_OK == res)
{
                                          /* Get CRC */
                                          Ipl_ClrTel();
                                          Ipl_IplData.Tel[0] = CMD_GETCRC;
                                          Ipl_IplData.Tel[3] = 0x2U;
                                          Ipl_IplData.TelLen = CMD_GETCRC_TXLEN;
                                          res = Ipl_ExecInicCmd();
                                          if (IPL_RES_OK == res)
{
                                              if ( (Ipl_IplData.Tel[4] != 0x00U) || (Ipl_IplData.Tel[5] != 0x00U) )
{
                                                  res = IPL_RES_ERR_WRONG_CRC;
                                              }
                                          }
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
         }
     }
     Ipl_ProgressIndicator(1U, 1U); /* Set Progress Indicator to 100 */
     Ipl_Trace(Ipl_TraceTag(res), "OS81050_ProgFirmware returned 0x%02X", res);
     return res;
 }
References CMD_CLEARCRC, CMD_CLEARCRC_TXLEN, CMD_ERASEPROGMEM, CMD_ERASEPROGMEM_TXLEN, CMD_GETCRC, CMD_GETCRC_TXLEN, CMD_SETPROGMEMPAGE, CMD_SETPROGMEMPAGE_TXLEN, CMD_WRITEPROGMEM, Ipl_CheckChipId(), Ipl_ClrTel(), Ipl_ExecInicCmd(), Ipl_IpfData, Ipl_IplData, Ipl_ParseIpf(), Ipl_PData(), Ipl_ProgressIndicator(), IPL_RES_ERR_WRONG_CRC, IPL_RES_OK, Ipl_Trace(), Ipl_TraceTag(), IPL_TRACETAG_INFO, Ipl_IpfData_::StringOffset, Ipl_IpfData_::StringSize, STRINGTYPE_FW, STRINGTYPE_META, Ipl_IplData_::Tel, and Ipl_IplData_::TelLen.
Referenced by OS81082_ProgFirmware().
OS81050_ProgIdentString()
uint8_t OS81050_ProgIdentString (uint32_t lData, uint8_t pData[])
Definition at line 254 of file ipl_81050.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81050_ProgIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81050_ProgPatchString()
uint8_t OS81050_ProgPatchString (uint32_t lData, uint8_t pData[])
Definition at line 261 of file ipl_81050.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81050_ProgPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81050_ProgTestConfigString()
uint8_t OS81050_ProgTestConfigString (uint32_t lData, uint8_t pData[])
Definition at line 282 of file ipl_81050.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81050_ProgTestConfigString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81050_ProgTestConfiguration()
uint8_t OS81050_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 268 of file ipl_81050.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81050_ProgTestConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81050_ProgTestIdentString()
uint8_t OS81050_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Definition at line 289 of file ipl_81050.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81050_ProgTestIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81050_ProgTestPatchString()
uint8_t OS81050_ProgTestPatchString (uint32_t lData, uint8_t pData[])
Definition at line 275 of file ipl_81050.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81050_ProgTestPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81050_ReadConfigStringVersion()
uint8_t OS81050_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
Definition at line 240 of file ipl_81050.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81050_ReadConfigStringVersion returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.