INIC PROGRAMMING LIBRARY: C:/Roland/AppsTeam/Misc/InicProgLib/trunk/ipl/opt/src/ipl_81060.c File Reference
ipl_81060.c File Reference
Internal OS81060 specific functions for INIC Programming Library.
#include <stdint.h>
#include "ipl_cfg.h"
#include "ipl.h"
#include "ipf.h"
#include "ipl_81060.h"
Functions
uint8_t OS81060_ProgConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ProgFirmware (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ProgConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ProgIdentString (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ProgPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ProgTestPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ProgTestConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81060_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Detailed Description
Internal OS81060 specific functions for INIC Programming Library.
Author
Roland Trissl (RTR)
Note
For support related to this code contact http://www.microchip.com/support.
Definition in file ipl_81060.c.
Function Documentation
OS81060_ProgConfigString()
uint8_t OS81060_ProgConfigString (uint32_t lData, uint8_t pData[])
Definition at line 41 of file ipl_81060.c.
 {
     uint8_t  res;
     uint32_t loop;
     Ipl_Trace(IPL_TRACETAG_INFO, "OS81060_ProgConfigString called");
     /* Get addresses and sizes from metadata */
     res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_META);
     if (IPL_RES_OK == res)
     {
         /* Check if IPF contains proper ConfigString */
         res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_CONFIG);
         if (IPL_RES_OK == res)
         {
             /* Check if IPF fits to INIC */
             res = Ipl_CheckChipId();
             if (IPL_RES_OK == res)
             {
                 /* Write CS */
                 Ipl_IplData.Tel[0] = CMD_LEG_WRITECS;
                 Ipl_IplData.Tel[1] = 0x00U;
                 Ipl_IplData.Tel[2] = 0x00U;
                 Ipl_IplData.Tel[3] = 0x20U;
                 for(loop=0U; loop<32U; loop++)
                 {
                     Ipl_IplData.Tel[4U+loop] = Ipl_PData(loop+Ipl_IpfData.StringOffset, lData, pData);
                 }
                 Ipl_IplData.TelLen = 36U;
                 res = Ipl_ExecInicCmd();
             }
         }
     }
     Ipl_Trace(Ipl_TraceTag(res), "OS81060_ProgConfigString returned 0x%02X", res);
     return res;
 }
References CMD_LEG_WRITECS, Ipl_CheckChipId(), Ipl_ExecInicCmd(), Ipl_IpfData, Ipl_IplData, Ipl_ParseIpf(), Ipl_PData(), IPL_RES_OK, Ipl_Trace(), Ipl_TraceTag(), IPL_TRACETAG_INFO, Ipl_IpfData_::StringOffset, STRINGTYPE_CONFIG, STRINGTYPE_META, Ipl_IplData_::Tel, and Ipl_IplData_::TelLen.
Referenced by OS81092_ProgConfigString().
OS81060_ProgConfiguration()
uint8_t OS81060_ProgConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 116 of file ipl_81060.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81060_ProgConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81060_ProgFirmware()
uint8_t OS81060_ProgFirmware (uint32_t lData, uint8_t pData[])
Definition at line 109 of file ipl_81060.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81060_ProgFirmware returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81060_ProgIdentString()
uint8_t OS81060_ProgIdentString (uint32_t lData, uint8_t pData[])
Definition at line 123 of file ipl_81060.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81060_ProgIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81060_ProgPatchString()
uint8_t OS81060_ProgPatchString (uint32_t lData, uint8_t pData[])
Definition at line 130 of file ipl_81060.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81060_ProgPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81060_ProgTestConfigString()
uint8_t OS81060_ProgTestConfigString (uint32_t lData, uint8_t pData[])
Definition at line 151 of file ipl_81060.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81060_ProgTestConfigString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81060_ProgTestConfiguration()
uint8_t OS81060_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 137 of file ipl_81060.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81060_ProgTestConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81060_ProgTestIdentString()
uint8_t OS81060_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Definition at line 158 of file ipl_81060.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81060_ProgTestIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81060_ProgTestPatchString()
uint8_t OS81060_ProgTestPatchString (uint32_t lData, uint8_t pData[])
Definition at line 144 of file ipl_81060.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81060_ProgTestPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81060_ReadConfigStringVersion()
uint8_t OS81060_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
Definition at line 78 of file ipl_81060.c.
 {
     uint8_t res;
     Ipl_Trace(IPL_TRACETAG_INFO, "OS81060_ReadConfigStringVersion called");
     /* Get CS Version */
     Ipl_ClrTel();
     Ipl_IplData.Tel[0] = CMD_LEG_GETCSINFO;
     Ipl_IplData.Tel[3] = 0x20U;
     Ipl_IplData.TelLen = CMD_LEG_GETCSINFO_TXLEN;
     res = Ipl_ExecInicCmd();
     if (IPL_RES_OK == res)
     {
         Ipl_InicData.CfgsVersionValid       = VERSION_VALID;
         Ipl_InicData.CfgsCustMajorVersion   = Ipl_IplData.Tel[6];
         Ipl_InicData.CfgsCustMinorVersion   = Ipl_IplData.Tel[7];
         Ipl_InicData.CfgsCustReleaseVersion = Ipl_IplData.Tel[8];
         Ipl_Trace(Ipl_TraceTag(res), "OS81060_ReadConfigStringVersion returned 0x%02X - V%u.%u.%u", res,
                   Ipl_InicData.CfgsCustMajorVersion, Ipl_InicData.CfgsCustMinorVersion, Ipl_InicData.CfgsCustReleaseVersion);
     }
     else
     {
         Ipl_Trace(Ipl_TraceTag(res), "OS81060_ReadConfigStringVersion returned 0x%02X", res);
     }
     return res;
 }
References Ipl_InicData_::CfgsCustMajorVersion, Ipl_InicData_::CfgsCustMinorVersion, Ipl_InicData_::CfgsCustReleaseVersion, Ipl_InicData_::CfgsVersionValid, CMD_LEG_GETCSINFO, CMD_LEG_GETCSINFO_TXLEN, Ipl_ClrTel(), Ipl_ExecInicCmd(), Ipl_InicData, Ipl_IplData, IPL_RES_OK, Ipl_Trace(), Ipl_TraceTag(), IPL_TRACETAG_INFO, Ipl_IplData_::Tel, Ipl_IplData_::TelLen, and VERSION_VALID.
Referenced by OS81092_ReadConfigStringVersion().