INIC PROGRAMMING LIBRARY: C:/Roland/AppsTeam/Misc/InicProgLib/trunk/ipl/opt/src/ipl_81092.c File Reference
ipl_81092.c File Reference
Internal OS81092 specific functions for INIC Programming Library.
#include <stdint.h>
#include "ipl_cfg.h"
#include "ipl.h"
#include "ipf.h"
#include "ipl_81092.h"
#include "ipl_81060.h"
Functions
uint8_t OS81092_ProgConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ProgFirmware (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ProgConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ProgIdentString (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ProgPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ProgTestPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ProgTestConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81092_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Detailed Description
Internal OS81092 specific functions for INIC Programming Library.
Author
Roland Trissl (RTR)
Note
For support related to this code contact http://www.microchip.com/support.
Definition in file ipl_81092.c.
Function Documentation
OS81092_ProgConfigString()
uint8_t OS81092_ProgConfigString (uint32_t lData, uint8_t pData[])
Definition at line 43 of file ipl_81092.c.
 {
     return OS81060_ProgConfigString(lData, pData);
 }
References OS81060_ProgConfigString().
OS81092_ProgConfiguration()
uint8_t OS81092_ProgConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 67 of file ipl_81092.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81092_ProgConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81092_ProgFirmware()
uint8_t OS81092_ProgFirmware (uint32_t lData, uint8_t pData[])
Definition at line 60 of file ipl_81092.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81092_ProgFirmware returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81092_ProgIdentString()
uint8_t OS81092_ProgIdentString (uint32_t lData, uint8_t pData[])
Definition at line 74 of file ipl_81092.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81092_ProgIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81092_ProgPatchString()
uint8_t OS81092_ProgPatchString (uint32_t lData, uint8_t pData[])
Definition at line 81 of file ipl_81092.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81092_ProgPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81092_ProgTestConfigString()
uint8_t OS81092_ProgTestConfigString (uint32_t lData, uint8_t pData[])
Definition at line 102 of file ipl_81092.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81092_ProgTestConfigString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81092_ProgTestConfiguration()
uint8_t OS81092_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 88 of file ipl_81092.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81092_ProgTestConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81092_ProgTestIdentString()
uint8_t OS81092_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Definition at line 109 of file ipl_81092.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81092_ProgTestIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81092_ProgTestPatchString()
uint8_t OS81092_ProgTestPatchString (uint32_t lData, uint8_t pData[])
Definition at line 95 of file ipl_81092.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81092_ProgTestPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81092_ReadConfigStringVersion()
uint8_t OS81092_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
Definition at line 50 of file ipl_81092.c.
 {
     return OS81060_ReadConfigStringVersion(lData, pData);
 }
References OS81060_ReadConfigStringVersion().