INIC PROGRAMMING LIBRARY: C:/Roland/AppsTeam/Misc/InicProgLib/trunk/ipl/opt/inc/ipl_81110.h File Reference
ipl_81110.h File Reference
Internal OS81110 specific header for INIC Programming Library.
#include <stdint.h>
#include "ipl_cfg.h"
Functions
uint8_t OS81110_ProgFirmware (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ProgConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ProgConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ProgPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ProgTestPatchString (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ProgTestConfigString (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ProgIdentString (uint32_t lData, uint8_t pData[])
uint8_t OS81110_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Detailed Description
Internal OS81110 specific header for INIC Programming Library.
Author
Roland Trissl (RTR)
Note
For support related to this code contact http://www.microchip.com/support.
Definition in file ipl_81110.h.
Function Documentation
OS81110_ProgConfigString()
uint8_t OS81110_ProgConfigString (uint32_t lData, uint8_t pData[])
Definition at line 170 of file ipl_81110.c.
 {
     uint8_t  res;
     uint32_t loop, page;
     Ipl_Trace(IPL_TRACETAG_INFO, "OS81110_ProgConfigString called");
     /* Get addresses and sizes from metadata */
     res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_META);
     if (IPL_RES_OK == res)
     {
         /* Check if IPF contains proper ConfigString */
         res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_CONFIG);
         if (IPL_RES_OK == res)
         {
             /* Check if IPF fits to INIC */
             res = Ipl_CheckChipId();
             if (IPL_RES_OK == res)
             {
                 /* Erase Enable */
                 Ipl_ClrTel();
                 Ipl_IplData.Tel[0] = CMD_LEG_ERASEENABLE;
                 Ipl_IplData.Tel[2] = 0x07U;
                 Ipl_IplData.TelLen = CMD_LEG_ERASEENABLE_TXLEN;
                 res = Ipl_ExecInicCmd();
                 if (IPL_RES_OK == res)
                 {
                     /* Erase INIC CS */
                     Ipl_ClrTel();
                     Ipl_IplData.Tel[0] = CMD_LEG_ERASECS;
                     Ipl_IplData.Tel[1] = 0x67U;
                     Ipl_IplData.TelLen = CMD_LEG_ERASECS_TXLEN;
                     res = Ipl_ExecInicCmd();
                     if (IPL_RES_OK == res)
                     {
                         /* Clear CRC */
                         Ipl_ClrTel();
                         Ipl_IplData.Tel[0] = CMD_CLEARCRC;
                         Ipl_IplData.TelLen = CMD_CLEARCRC_TXLEN;
                         res = Ipl_ExecInicCmd();
                         if (IPL_RES_OK == res)
{
                             /* Write CS */
                             for(page=0U; page<=3U; page++)
{
                                 Ipl_IplData.Tel[0] = CMD_LEG_WRITECS;
                                 Ipl_IplData.Tel[1] = 0x00U;
                                 Ipl_IplData.Tel[2] = (uint8_t) page*32U;
                                 Ipl_IplData.Tel[3] = 0x20U;
                                 for(loop=0U; loop<32U; loop++)
{
                                     Ipl_IplData.Tel[4U+loop] = Ipl_PData(loop+Ipl_IpfData.StringOffset+(uint32_t) (page*32U), lData, pData);
                                 }
                                 Ipl_IplData.TelLen = 36U;
                                 res = Ipl_ExecInicCmd();
                                 Ipl_ProgressIndicator((page*32U), Ipl_IpfData.StringSize);
                             }
                             if (IPL_RES_OK == res)
{
                                 /* Get CRC */
                                 Ipl_ClrTel();
                                 Ipl_IplData.Tel[0] = CMD_GETCRC;
                                 Ipl_IplData.Tel[3] = 0x2U;
                                 Ipl_IplData.TelLen = CMD_GETCRC_TXLEN;
                                 res = Ipl_ExecInicCmd();
                                 if(IPL_RES_OK == res)
{
                                     if ( (Ipl_IplData.Tel[4] != 0x00U) || (Ipl_IplData.Tel[5] != 0x00U) )
{
                                         res = IPL_RES_ERR_WRONG_CRC;
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
         }
     }
     Ipl_ProgressIndicator(1U, 1U); /* Set Progress Indicator to 100 */
     Ipl_Trace(Ipl_TraceTag(res), "OS81110_ProgConfigString returned 0x%02X", res);
     return res;
 }
References CMD_CLEARCRC, CMD_CLEARCRC_TXLEN, CMD_GETCRC, CMD_GETCRC_TXLEN, CMD_LEG_ERASECS, CMD_LEG_ERASECS_TXLEN, CMD_LEG_ERASEENABLE, CMD_LEG_ERASEENABLE_TXLEN, CMD_LEG_WRITECS, Ipl_CheckChipId(), Ipl_ClrTel(), Ipl_ExecInicCmd(), Ipl_IpfData, Ipl_IplData, Ipl_ParseIpf(), Ipl_PData(), Ipl_ProgressIndicator(), IPL_RES_ERR_WRONG_CRC, IPL_RES_OK, Ipl_Trace(), Ipl_TraceTag(), IPL_TRACETAG_INFO, Ipl_IpfData_::StringOffset, Ipl_IpfData_::StringSize, STRINGTYPE_CONFIG, STRINGTYPE_META, Ipl_IplData_::Tel, and Ipl_IplData_::TelLen.
OS81110_ProgConfiguration()
uint8_t OS81110_ProgConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 285 of file ipl_81110.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81110_ProgConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81110_ProgFirmware()
uint8_t OS81110_ProgFirmware (uint32_t lData, uint8_t pData[])
Definition at line 41 of file ipl_81110.c.
 {
     uint8_t  res;
     uint32_t loop, adr, startadr, stopadr;
     Ipl_Trace(IPL_TRACETAG_INFO, "OS81110_ProgFirmware called");
     /* Get addresses and sizes from metadata */
     res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_META);
     if (IPL_RES_OK == res)
     {
         /* Check if IPF contains proper Firmware */
         res = Ipl_ParseIpf(&Ipl_IpfData, lData, pData, STRINGTYPE_FW);
         if (IPL_RES_OK == res)
         {
             /* Check if IPF fits to INIC */
             res = Ipl_CheckChipId();
             if (IPL_RES_OK == res)
             {
                 /* Erase Enable */
                 Ipl_ClrTel();
                 Ipl_IplData.Tel[0] = CMD_LEG_ERASEENABLE;
                 Ipl_IplData.Tel[2] = 0x07U;
                 Ipl_IplData.TelLen = CMD_LEG_ERASEENABLE_TXLEN;
                 res = Ipl_ExecInicCmd();
                 if (IPL_RES_OK == res)
                 {
                     /* Erase INIC FW */
                     Ipl_ClrTel();
                     Ipl_IplData.Tel[0] = CMD_ERASEPROGMEM;
                     Ipl_IplData.Tel[1] = 0x06U;
                     Ipl_IplData.Tel[2] = 0x7AU;
                     Ipl_IplData.TelLen = CMD_ERASEPROGMEM_TXLEN;
                     res = Ipl_ExecInicCmd();
                     if (IPL_RES_OK == res)
                     {
                         /* Select Flash Page 0 */
                         Ipl_ClrTel();
                         Ipl_IplData.Tel[0] = CMD_SETPROGMEMPAGE;
                         Ipl_IplData.Tel[1] = 0x0U;
                         Ipl_IplData.TelLen = CMD_SETPROGMEMPAGE_TXLEN;
                         res = Ipl_ExecInicCmd();
                         if (IPL_RES_OK == res)
{
                             /* Clear CRC */
                             Ipl_ClrTel();
                             Ipl_IplData.Tel[0] = CMD_CLEARCRC;
                             Ipl_IplData.TelLen = CMD_CLEARCRC_TXLEN;
                             res = Ipl_ExecInicCmd();
                             if (IPL_RES_OK == res)
{
                                 /* Write FW Page 0 */
                                 startadr = 0x1800U;
                                 adr      = startadr;
                                 stopadr = 0x10000U;
                                 while ( (adr < stopadr) && (IPL_RES_OK == res) )
{
                                     Ipl_IplData.Tel[0] = CMD_WRITEPROGMEM;
                                     Ipl_IplData.Tel[1] = (adr >> 8U) & 0xFFU;
                                     Ipl_IplData.Tel[2] = adr & 0xFFU;
                                     Ipl_IplData.Tel[3] = 0x20U;
                                     for(loop=0U; loop<32U; loop++)
{
                                         Ipl_IplData.Tel[4U+loop] = Ipl_PData((loop+Ipl_IpfData.StringOffset+adr)-startadr, lData, pData);
                                     }
                                     Ipl_IplData.TelLen = 36U;
                                     res = Ipl_ExecInicCmd();
                                     adr += 0x20U;
                                     Ipl_ProgressIndicator(adr-startadr, Ipl_IpfData.StringSize);
                                 }
                                 if (IPL_RES_OK == res)
{
                                     /* Select Flash Page 1 */
                                     Ipl_ClrTel();
                                     Ipl_IplData.Tel[0] = CMD_SETPROGMEMPAGE;
                                     Ipl_IplData.Tel[1] = 0x1U;
                                     Ipl_IplData.TelLen = CMD_SETPROGMEMPAGE_TXLEN;
                                     res = Ipl_ExecInicCmd();
                                     if (IPL_RES_OK == res)
{
                                         /* Write FW Page 1 */
                                         adr     = 0x10000U;
                                         stopadr = 0x1FFFFU;
                                         while ( (adr < stopadr) && (IPL_RES_OK == res) )
{
                                             Ipl_IplData.Tel[0] = CMD_WRITEPROGMEM;
                                             Ipl_IplData.Tel[1] = (adr >> 8U) & 0xFFU;
                                             Ipl_IplData.Tel[2] = adr & 0xFFU;
                                             Ipl_IplData.Tel[3] = 0x20U;
                                             for(loop=0U; loop<32U; loop++)
{
                                                 Ipl_IplData.Tel[4U+loop] = Ipl_PData((loop+Ipl_IpfData.StringOffset+adr)-startadr, lData, pData);
                                             }
                                             Ipl_IplData.TelLen = 36U;
                                             res = Ipl_ExecInicCmd();
                                             adr += 0x20U;
                                             Ipl_ProgressIndicator(adr-startadr, Ipl_IpfData.StringSize);
                                         }
                                         if (IPL_RES_OK == res)
{
                                             /* Get CRC */
                                             Ipl_ClrTel();
                                             Ipl_IplData.Tel[0] = CMD_GETCRC;
                                             Ipl_IplData.Tel[3] = 0x2U;
                                             Ipl_IplData.TelLen = CMD_GETCRC_TXLEN;
                                             res = Ipl_ExecInicCmd();
                                             if (IPL_RES_OK == res)
{
                                                 if ( (Ipl_IplData.Tel[4] != 0x00U) || (Ipl_IplData.Tel[5] != 0x00U) )
{
                                                     res = IPL_RES_ERR_WRONG_CRC;
                                                 }
                                             }
                                         }
                                     }
                                 }
                             }
                         }
                     }
                 }
             }
         }
     }
     Ipl_ProgressIndicator(1U, 1U); /* Set Progress Indicator to 100 */
     Ipl_Trace(Ipl_TraceTag(res), "OS81110_ProgFirmware returned 0x%02X", res);
     return res;
 }
References CMD_CLEARCRC, CMD_CLEARCRC_TXLEN, CMD_ERASEPROGMEM, CMD_ERASEPROGMEM_TXLEN, CMD_GETCRC, CMD_GETCRC_TXLEN, CMD_LEG_ERASEENABLE, CMD_LEG_ERASEENABLE_TXLEN, CMD_SETPROGMEMPAGE, CMD_SETPROGMEMPAGE_TXLEN, CMD_WRITEPROGMEM, Ipl_CheckChipId(), Ipl_ClrTel(), Ipl_ExecInicCmd(), Ipl_IpfData, Ipl_IplData, Ipl_ParseIpf(), Ipl_PData(), Ipl_ProgressIndicator(), IPL_RES_ERR_WRONG_CRC, IPL_RES_OK, Ipl_Trace(), Ipl_TraceTag(), IPL_TRACETAG_INFO, Ipl_IpfData_::StringOffset, Ipl_IpfData_::StringSize, STRINGTYPE_FW, STRINGTYPE_META, Ipl_IplData_::Tel, and Ipl_IplData_::TelLen.
OS81110_ProgIdentString()
uint8_t OS81110_ProgIdentString (uint32_t lData, uint8_t pData[])
Definition at line 292 of file ipl_81110.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81110_ProgIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81110_ProgPatchString()
uint8_t OS81110_ProgPatchString (uint32_t lData, uint8_t pData[])
Definition at line 299 of file ipl_81110.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81110_ProgPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81110_ProgTestConfigString()
uint8_t OS81110_ProgTestConfigString (uint32_t lData, uint8_t pData[])
Definition at line 320 of file ipl_81110.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81110_ProgTestConfigString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81110_ProgTestConfiguration()
uint8_t OS81110_ProgTestConfiguration (uint32_t lData, uint8_t pData[])
Definition at line 306 of file ipl_81110.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81110_ProgTestConfiguration returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81110_ProgTestIdentString()
uint8_t OS81110_ProgTestIdentString (uint32_t lData, uint8_t pData[])
Definition at line 327 of file ipl_81110.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81110_ProgTestIdentString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81110_ProgTestPatchString()
uint8_t OS81110_ProgTestPatchString (uint32_t lData, uint8_t pData[])
Definition at line 313 of file ipl_81110.c.
 {
     Ipl_Trace(IPL_TRACETAG_ERR, "OS81110_ProgTestPatchString returned 0x%02X", IPL_RES_ERR_NOT_SUPPORTED);
     return IPL_RES_ERR_NOT_SUPPORTED;
 }
References IPL_RES_ERR_NOT_SUPPORTED, Ipl_Trace(), and IPL_TRACETAG_ERR.
OS81110_ReadConfigStringVersion()
uint8_t OS81110_ReadConfigStringVersion (uint32_t lData, uint8_t pData[])
Definition at line 254 of file ipl_81110.c.
 {
     uint8_t res;
     Ipl_Trace(IPL_TRACETAG_INFO, "OS81110_ReadConfigStringVersion called");
     /* Get CS Version */
     Ipl_ClrTel();
     Ipl_IplData.Tel[0] = CMD_LEG_GETCSINFO;
     Ipl_IplData.Tel[3] = 0x1AU;
     Ipl_IplData.TelLen = CMD_LEG_GETCSINFO_TXLEN;
     res = Ipl_ExecInicCmd();
     if (IPL_RES_OK == res)
     {
         Ipl_InicData.CfgsVersionValid       = VERSION_VALID;
         Ipl_InicData.CfgsCustMajorVersion   = Ipl_IplData.Tel[27];
         Ipl_InicData.CfgsCustMinorVersion   = Ipl_IplData.Tel[28];
         Ipl_InicData.CfgsCustReleaseVersion = Ipl_IplData.Tel[29];
         Ipl_Trace(Ipl_TraceTag(res), "OS81110_ReadConfigStringVersion returned 0x%02X - V%u.%u.%u", res,
                   Ipl_InicData.CfgsCustMajorVersion, Ipl_InicData.CfgsCustMinorVersion, Ipl_InicData.CfgsCustReleaseVersion);
     }
     else
     {
         Ipl_Trace(Ipl_TraceTag(res), "OS81110_ReadConfigStringVersion returned 0x%02X", res);
     }
     return res;
 }
References Ipl_InicData_::CfgsCustMajorVersion, Ipl_InicData_::CfgsCustMinorVersion, Ipl_InicData_::CfgsCustReleaseVersion, Ipl_InicData_::CfgsVersionValid, CMD_LEG_GETCSINFO, CMD_LEG_GETCSINFO_TXLEN, Ipl_ClrTel(), Ipl_ExecInicCmd(), Ipl_InicData, Ipl_IplData, IPL_RES_OK, Ipl_Trace(), Ipl_TraceTag(), IPL_TRACETAG_INFO, Ipl_IplData_::Tel, Ipl_IplData_::TelLen, and VERSION_VALID.